// Longtail Swap UI Component
// Generated by Cradle - https://cradle-web-eight.vercel.app

'use client';

import { useState } from 'react';
import { parseUnits, formatUnits } from 'viem';
import type { Address } from 'viem';
import { useLongtailSwap } from '../hooks/useLongtailSwap';

// Token list for Superposition (verified from docs.long.so)
const TOKENS = [
  { symbol: 'ETH', address: '0x0000000000000000000000000000000000000000' as Address, decimals: 18 },
  { symbol: 'WETH', address: '0x1fB719f10b56d7a85DCD32f27f897375fB21cfdd' as Address, decimals: 18 },
  { symbol: 'USDC', address: '0x6c030c5CC283F791B26816f325b9C632d964F8A1' as Address, decimals: 6 },
  { symbol: 'ARB', address: '0xA2555701754464d32D9624149E3fDb459F3c8DE4' as Address, decimals: 18 },
];

interface LongtailSwapProps {
  className?: string;
}

export function LongtailSwap({ className }: LongtailSwapProps) {
  const { status, quote, error, txHash, getQuote, swap, reset } = useLongtailSwap();

  const [tokenIn, setTokenIn] = useState(TOKENS[0]);
  const [tokenOut, setTokenOut] = useState(TOKENS[1]);
  const [amountIn, setAmountIn] = useState('');

  const handleGetQuote = async () => {
    if (!amountIn) return;
    const amount = parseUnits(amountIn, tokenIn.decimals);
    await getQuote(tokenIn.address, tokenOut.address, amount);
  };

  const handleSwap = async () => {
    if (!amountIn) return;
    const amount = parseUnits(amountIn, tokenIn.decimals);
    await swap(tokenIn.address, tokenOut.address, amount);
  };

  const handleSwitchTokens = () => {
    const temp = tokenIn;
    setTokenIn(tokenOut);
    setTokenOut(temp);
    setAmountIn('');
    reset();
  };

  return (
    <div className={`longtail-swap ${className || ''}`}>
      <h2 className="text-xl font-bold mb-4">Swap on Longtail</h2>
      
      {/* Token In */}
      <div className="mb-4 p-4 border rounded">
        <label className="block text-sm font-medium mb-2">From</label>
        <div className="flex gap-2">
          <select
            value={tokenIn.symbol}
            onChange={(e) => {
              const token = TOKENS.find(t => t.symbol === e.target.value);
              if (token) setTokenIn(token);
            }}
            className="p-2 border rounded"
          >
            {TOKENS.map(token => (
              <option key={token.symbol} value={token.symbol}>
                {token.symbol}
              </option>
            ))}
          </select>
          <input
            type="number"
            value={amountIn}
            onChange={(e) => setAmountIn(e.target.value)}
            placeholder="0.0"
            className="flex-1 p-2 border rounded"
          />
        </div>
      </div>

      {/* Switch Button */}
      <div className="flex justify-center mb-4">
        <button
          onClick={handleSwitchTokens}
          className="p-2 border rounded-full hover:bg-gray-100"
        >
          ↕️
        </button>
      </div>

      {/* Token Out */}
      <div className="mb-4 p-4 border rounded">
        <label className="block text-sm font-medium mb-2">To</label>
        <div className="flex gap-2">
          <select
            value={tokenOut.symbol}
            onChange={(e) => {
              const token = TOKENS.find(t => t.symbol === e.target.value);
              if (token) setTokenOut(token);
            }}
            className="p-2 border rounded"
          >
            {TOKENS.map(token => (
              <option key={token.symbol} value={token.symbol}>
                {token.symbol}
              </option>
            ))}
          </select>
          <input
            type="text"
            value={quote ? formatUnits(quote.amountOut, tokenOut.decimals) : ''}
            placeholder="0.0"
            className="flex-1 p-2 border rounded bg-gray-50"
            readOnly
          />
        </div>
      </div>

      {/* Quote Details */}
      {quote && (
        <div className="mb-4 p-3 bg-gray-100 rounded text-sm">
          <p>Price Impact: {quote.priceImpact.toFixed(2)}%</p>
          <p>Route: {quote.route.map(r => `${r.fee/10000}%`).join(' → ')}</p>
        </div>
      )}

      {/* Error */}
      {error && (
        <div className="mb-4 p-3 bg-red-100 text-red-700 rounded">
          {error.message}
        </div>
      )}

      {/* Success */}
      {txHash && (
        <div className="mb-4 p-3 bg-green-100 text-green-700 rounded">
          <p>Swap successful!</p>
          <a
            href={`https://explorer.superposition.so/tx/${txHash}`}
            target="_blank"
            rel="noopener noreferrer"
            className="underline"
          >
            View transaction
          </a>
        </div>
      )}

      {/* Actions */}
      <div className="flex gap-2">
        <button
          onClick={handleGetQuote}
          disabled={!amountIn || status !== 'idle'}
          className="flex-1 p-3 bg-blue-500 text-white rounded hover:bg-blue-600 disabled:opacity-50"
        >
          {status === 'fetching-quote' ? 'Getting Quote...' : 'Get Quote'}
        </button>
        <button
          onClick={handleSwap}
          disabled={!quote || status !== 'idle'}
          className="flex-1 p-3 bg-green-500 text-white rounded hover:bg-green-600 disabled:opacity-50"
        >
          {status === 'swapping' ? 'Swapping...' : 'Swap'}
        </button>
      </div>

      <p className="mt-4 text-xs text-gray-500 text-center">
        Every swap on Longtail earns yield rewards through Utility Mining
      </p>
    </div>
  );
}