// Superposition Bridge UI Component
// Generated by Cradle - https://cradle-web-eight.vercel.app

'use client';

import { useState } from 'react';
import { useSuperpositionBridge } from '../hooks/useSuperpositionBridge';
import type { BridgeToken, SourceChain } from '../types/bridge';

interface SuperpositionBridgeProps {
  className?: string;
}

export function SuperpositionBridge({ className }: SuperpositionBridgeProps) {
  const {
    status,
    quote,
    error,
    txHash,
    isLoading,
    getQuote,
    bridge,
    reset,
    supportedTokens,
    sourceChains,
  } = useSuperpositionBridge();

  const [sourceChain, setSourceChain] = useState<SourceChain>(sourceChains[0]);
  const [token, setToken] = useState<BridgeToken>(supportedTokens[0]);
  const [amount, setAmount] = useState('');

  const handleGetQuote = async () => {
    if (!amount) return;
    await getQuote(sourceChain, token, BigInt(parseFloat(amount) * 1e18));
  };

  const handleBridge = async () => {
    if (!amount) return;
    await bridge(sourceChain, token, BigInt(parseFloat(amount) * 1e18));
  };

  return (
    <div className={`superposition-bridge ${className || ''}`}>
      <h2 className="text-xl font-bold mb-4">Bridge to Superposition</h2>
      
      {/* Source Chain Selector */}
      <div className="mb-4">
        <label className="block text-sm font-medium mb-1">From Chain</label>
        <select
          value={sourceChain}
          onChange={(e) => setSourceChain(e.target.value as SourceChain)}
          className="w-full p-2 border rounded"
          disabled={isLoading}
        >
          {sourceChains.map((chain) => (
            <option key={chain} value={chain}>
              {chain.charAt(0).toUpperCase() + chain.slice(1)}
            </option>
          ))}
        </select>
      </div>

      {/* Token Selector */}
      <div className="mb-4">
        <label className="block text-sm font-medium mb-1">Token</label>
        <select
          value={token}
          onChange={(e) => setToken(e.target.value as BridgeToken)}
          className="w-full p-2 border rounded"
          disabled={isLoading}
        >
          {supportedTokens.map((t) => (
            <option key={t} value={t}>{t}</option>
          ))}
        </select>
      </div>

      {/* Amount Input */}
      <div className="mb-4">
        <label className="block text-sm font-medium mb-1">Amount</label>
        <input
          type="number"
          value={amount}
          onChange={(e) => setAmount(e.target.value)}
          placeholder="0.0"
          className="w-full p-2 border rounded"
          disabled={isLoading}
        />
      </div>

      {/* Quote Display */}
      {quote && (
        <div className="mb-4 p-3 bg-gray-100 rounded">
          <p className="text-sm">
            You will receive: ~{(Number(quote.toAmount) / 1e18).toFixed(6)} {token}
          </p>
          <p className="text-xs text-gray-600">
            Estimated time: {Math.ceil(quote.route.estimatedTime / 60)} min
          </p>
          <p className="text-xs text-gray-600">
            Route: {quote.route.provider}
          </p>
        </div>
      )}

      {/* Error Display */}
      {error && (
        <div className="mb-4 p-3 bg-red-100 text-red-700 rounded">
          {error.message}
        </div>
      )}

      {/* Success Display */}
      {txHash && (
        <div className="mb-4 p-3 bg-green-100 text-green-700 rounded">
          <p>Bridge initiated!</p>
          <a
            href={`https://explorer.superposition.so/tx/${txHash}`}
            target="_blank"
            rel="noopener noreferrer"
            className="underline"
          >
            View on Explorer
          </a>
        </div>
      )}

      {/* Action Buttons */}
      <div className="flex gap-2">
        <button
          onClick={handleGetQuote}
          disabled={isLoading || !amount}
          className="flex-1 p-2 bg-blue-500 text-white rounded hover:bg-blue-600 disabled:opacity-50"
        >
          {status === 'fetching-quote' ? 'Getting Quote...' : 'Get Quote'}
        </button>
        <button
          onClick={handleBridge}
          disabled={isLoading || !quote}
          className="flex-1 p-2 bg-green-500 text-white rounded hover:bg-green-600 disabled:opacity-50"
        >
          {status === 'bridging' ? 'Bridging...' : 'Bridge'}
        </button>
      </div>

      {/* Status */}
      <p className="mt-2 text-sm text-gray-600 text-center">
        Status: {status}
      </p>
    </div>
  );
}