// Longtail Pool Queries Hook
// Generated by Cradle - https://cradle-web-eight.vercel.app

'use client';

import { useCallback } from 'react';
import { usePublicClient } from 'wagmi';
import type { Address } from 'viem';
import type { LongtailPool } from '../types/longtail';
import { LONGTAIL_FACTORY_ABI, LONGTAIL_POOL_ABI } from '../abi/longtail';
import { getSuperpositionContracts } from '../config/superposition-constants';
import { useQuery } from '@tanstack/react-query';

/**
 * Hook for querying Longtail pool information
 */
export function useLongtailPool(
  token0: Address,
  token1: Address,
  fee: number = 3000
) {
  const publicClient = usePublicClient();
  const contracts = getSuperpositionContracts(55244);

  const { data: pool, isLoading, error, refetch } = useQuery({
    queryKey: ['longtail-pool', token0, token1, fee],
    queryFn: async (): Promise<LongtailPool | null> => {
      if (!publicClient) return null;

      try {
        // Get pool address from Longtail AMM (0xF3334049A3ce7e890bd4f8C6a0FBC70e38fd3746)
        const poolAddress = await publicClient.readContract({
          address: contracts.LONGTAIL_AMM,
          abi: LONGTAIL_FACTORY_ABI,
          functionName: 'getPool',
          args: [token0, token1, fee],
        });

        if (poolAddress === '0x0000000000000000000000000000000000000000') {
          return null;
        }

        // Get pool data
        const [slot0, liquidity, poolToken0, poolToken1, poolFee] = await Promise.all([
          publicClient.readContract({
            address: poolAddress,
            abi: LONGTAIL_POOL_ABI,
            functionName: 'slot0',
          }),
          publicClient.readContract({
            address: poolAddress,
            abi: LONGTAIL_POOL_ABI,
            functionName: 'liquidity',
          }),
          publicClient.readContract({
            address: poolAddress,
            abi: LONGTAIL_POOL_ABI,
            functionName: 'token0',
          }),
          publicClient.readContract({
            address: poolAddress,
            abi: LONGTAIL_POOL_ABI,
            functionName: 'token1',
          }),
          publicClient.readContract({
            address: poolAddress,
            abi: LONGTAIL_POOL_ABI,
            functionName: 'fee',
          }),
        ]);

        return {
          address: poolAddress,
          token0: poolToken0,
          token1: poolToken1,
          fee: Number(poolFee),
          liquidity: BigInt(liquidity),
          sqrtPriceX96: slot0[0],
          tick: slot0[1],
          token0Symbol: 'TOKEN0', // Would fetch from token contract
          token1Symbol: 'TOKEN1',
          tvlUsd: 0, // Would calculate from price feed
          volume24h: 0,
          apr: 0,
        };
      } catch (err) {
        console.error('Failed to fetch pool:', err);
        return null;
      }
    },
    enabled: !!publicClient && !!token0 && !!token1,
    staleTime: 30_000, // 30 seconds
  });

  return {
    pool,
    isLoading,
    error,
    refetch,
  };
}

/**
 * Hook for listing all pools
 */
export function useLongtailPools() {
  // In production, this would fetch from an indexer or subgraph
  const { data: pools, isLoading, error } = useQuery({
    queryKey: ['longtail-pools'],
    queryFn: async (): Promise<LongtailPool[]> => {
      // Placeholder - would fetch from API/subgraph
      return [];
    },
    staleTime: 60_000, // 1 minute
  });

  return {
    pools: pools ?? [],
    isLoading,
    error,
  };
}