// Superposition Withdraw Hook
// Generated by Cradle - https://cradle-web-eight.vercel.app

'use client';

import { useState, useCallback } from 'react';
import { useAccount, useWalletClient } from 'wagmi';
import type { Address } from 'viem';
import { getRoutes, executeRoute } from '@lifi/sdk';
import type { BridgeStatus, BridgeToken, SourceChain } from '../types/bridge';

const SUPERPOSITION_CHAIN_ID = 55244;

/**
 * Hook for withdrawing assets from Superposition
 */
export function useSuperpositionWithdraw() {
  const { address } = useAccount();
  const { data: walletClient } = useWalletClient();

  const [status, setStatus] = useState<BridgeStatus>('idle');
  const [error, setError] = useState<Error | null>(null);
  const [txHash, setTxHash] = useState<string | null>(null);

  const withdraw = useCallback(
    async (
      destinationChain: SourceChain,
      token: BridgeToken,
      amount: bigint
    ): Promise<string | null> => {
      if (!address || !walletClient) {
        setError(new Error('Wallet not connected'));
        return null;
      }

      setStatus('bridging');
      setError(null);

      try {
        // Get routes from Superposition to destination
        const routes = await getRoutes({
          fromChainId: SUPERPOSITION_CHAIN_ID,
          toChainId: getChainId(destinationChain),
          fromTokenAddress: '0x0000000000000000000000000000000000000000', // Update with actual token
          toTokenAddress: '0x0000000000000000000000000000000000000000',
          fromAmount: amount.toString(),
          fromAddress: address,
          toAddress: address,
        });

        if (!routes.routes || routes.routes.length === 0) {
          throw new Error('No withdraw routes found');
        }

        const result = await executeRoute(routes.routes[0], {});

        setTxHash(result.transactionHash || null);
        setStatus('completed');

        return result.transactionHash || null;
      } catch (err) {
        const error = err instanceof Error ? err : new Error('Withdraw failed');
        setError(error);
        setStatus('error');
        return null;
      }
    },
    [address, walletClient]
  );

  return {
    status,
    error,
    txHash,
    withdraw,
    isLoading: status === 'bridging' || status === 'waiting-confirmation',
  };
}

function getChainId(chain: SourceChain): number {
  const chainIds: Record<SourceChain, number> = {
    arbitrum: 42161,
    ethereum: 1,
    optimism: 10,
    base: 8453,
  };
  return chainIds[chain];
}