// Superposition Bridge Types
// Generated by Cradle - https://cradle-web-eight.vercel.app

import type { Address } from 'viem';

export type BridgeToken = 'ETH' | 'USDC';
export type SourceChain = 'arbitrum';

export interface BridgeQuote {
  fromChainId: number;
  toChainId: number;
  fromToken: Address;
  toToken: Address;
  fromAmount: bigint;
  toAmount: bigint;
  estimatedGas: bigint;
  bridgeFee: bigint;
  route: BridgeRoute;
}

export interface BridgeRoute {
  provider: string;
  steps: BridgeStep[];
  estimatedTime: number; // seconds
}

export interface BridgeStep {
  type: 'swap' | 'bridge' | 'approve';
  tool: string;
  fromChain: number;
  toChain: number;
  fromToken: Address;
  toToken: Address;
  fromAmount: string;
  toAmount: string;
}

export interface BridgeTransaction {
  hash: string;
  status: 'pending' | 'completed' | 'failed';
  fromChain: number;
  toChain: number;
  amount: bigint;
  token: Address;
  timestamp: number;
}

export type BridgeStatus = 
  | 'idle'
  | 'fetching-quote'
  | 'approving'
  | 'bridging'
  | 'waiting-confirmation'
  | 'completed'
  | 'error';